{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "54e9ccfe-f7d4-48e3-89df-65063a1368e1",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "=======================================================\n",
    "  BASE SCRAPER — Classe mère commune à tous les scrapers\n",
    "  Chaque scraper hérite de cette classe et implémente\n",
    "  uniquement la méthode scrape()\n",
    "=======================================================\n",
    "\"\"\"\n",
    "\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import pandas as pd\n",
    "import time\n",
    "import json\n",
    "import os\n",
    "from datetime import datetime\n",
    "from abc import ABC, abstractmethod\n",
    "\n",
    "\n",
    "HEADERS = {\n",
    "    \"User-Agent\": (\n",
    "        \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) \"\n",
    "        \"AppleWebKit/537.36 (KHTML, like Gecko) \"\n",
    "        \"Chrome/120.0.0.0 Safari/537.36\"\n",
    "    ),\n",
    "    \"Accept-Language\": \"fr-FR,fr;q=0.9\",\n",
    "    \"Accept\": \"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\",\n",
    "}\n",
    "\n",
    "# ── Schéma standard : toutes les données doivent respecter ce format ──\n",
    "SCHEMA = {\n",
    "    \"username\":              \"\",\n",
    "    \"nom\":                   \"\",\n",
    "    \"categorie\":             \"\",\n",
    "    \"biographie\":            \"\",\n",
    "    \"instagram_followers\":   0,\n",
    "    \"instagram_following\":   0,\n",
    "    \"instagram_posts\":       0,\n",
    "    \"tiktok_followers\":      0,\n",
    "    \"tiktok_following\":      0,\n",
    "    \"tiktok_likes\":          0,\n",
    "    \"youtube_subscribers\":   0,\n",
    "    \"youtube_views\":         0,\n",
    "    \"twitter_followers\":     0,\n",
    "    \"score_influence\":       0.0,\n",
    "    \"url_profil\":            \"\",\n",
    "    \"photo_url\":             \"\",\n",
    "    \"source\":                \"\",       # ← site d'où vient la donnée\n",
    "    \"date_collecte\":         \"\",\n",
    "}\n",
    "\n",
    "\n",
    "class BaseScraper(ABC):\n",
    "    \"\"\"\n",
    "    Classe mère que chaque scraper doit hériter.\n",
    "    Fournit :\n",
    "      - get()          : requête HTTP avec gestion d'erreurs\n",
    "      - parse()        : BeautifulSoup prêt à l'emploi\n",
    "      - normaliser()   : force le schéma standard sur un dict\n",
    "      - convertir_stat(): \"16.7M+\" → 16700000\n",
    "      - sauvegarder()  : sauvegarde CSV dans data/raw/\n",
    "      - run()          : orchestre tout\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, nom_source, pause=2):\n",
    "        self.nom_source = nom_source\n",
    "        self.pause = pause\n",
    "        self.resultats = []\n",
    "        os.makedirs(\"data/raw\", exist_ok=True)\n",
    "\n",
    "    # ──────────────────────────────────────────\n",
    "    #  Requête HTTP\n",
    "    # ──────────────────────────────────────────\n",
    "    def get(self, url, timeout=15):\n",
    "        \"\"\"Envoie une requête GET et retourne la réponse ou None\"\"\"\n",
    "        try:\n",
    "            response = requests.get(url, headers=HEADERS, timeout=timeout)\n",
    "            response.raise_for_status()\n",
    "            time.sleep(self.pause)\n",
    "            return response\n",
    "        except requests.exceptions.HTTPError as e:\n",
    "            print(f\"    ⚠️  HTTP {e.response.status_code} pour {url}\")\n",
    "        except requests.exceptions.ConnectionError:\n",
    "            print(f\"    ⚠️  Connexion impossible : {url}\")\n",
    "        except requests.exceptions.Timeout:\n",
    "            print(f\"    ⚠️  Timeout : {url}\")\n",
    "        except Exception as e:\n",
    "            print(f\"    ⚠️  Erreur inconnue : {e}\")\n",
    "        return None\n",
    "\n",
    "    # ──────────────────────────────────────────\n",
    "    #  Parser HTML\n",
    "    # ──────────────────────────────────────────\n",
    "    def parse(self, response):\n",
    "        \"\"\"Retourne un objet BeautifulSoup depuis une réponse\"\"\"\n",
    "        return BeautifulSoup(response.content, \"html.parser\")\n",
    "\n",
    "    # ──────────────────────────────────────────\n",
    "    #  Normaliser un dict vers le schéma standard\n",
    "    # ──────────────────────────────────────────\n",
    "    def normaliser(self, data: dict) -> dict:\n",
    "        \"\"\"\n",
    "        Prend n'importe quel dict et le force dans le schéma standard.\n",
    "        Les clés inconnues sont ignorées, les clés manquantes prennent\n",
    "        la valeur par défaut du schéma.\n",
    "        \"\"\"\n",
    "        record = dict(SCHEMA)           # Copie du schéma avec valeurs par défaut\n",
    "        for key in SCHEMA:\n",
    "            if key in data:\n",
    "                record[key] = data[key]\n",
    "        record[\"source\"]        = self.nom_source\n",
    "        record[\"date_collecte\"] = datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n",
    "        return record\n",
    "\n",
    "    # ──────────────────────────────────────────\n",
    "    #  Convertir \"16.7M +\" → 16700000\n",
    "    # ──────────────────────────────────────────\n",
    "    @staticmethod\n",
    "    def convertir_stat(valeur_str):\n",
    "        if not valeur_str:\n",
    "            return 0\n",
    "        s = str(valeur_str).upper().replace(\" \", \"\").replace(\"+\", \"\").strip()\n",
    "        try:\n",
    "            if \"M\" in s:\n",
    "                return int(float(s.replace(\"M\", \"\")) * 1_000_000)\n",
    "            elif \"K\" in s:\n",
    "                return int(float(s.replace(\"K\", \"\")) * 1_000)\n",
    "            else:\n",
    "                return int(float(s.replace(\",\", \".\")))\n",
    "        except ValueError:\n",
    "            return 0\n",
    "\n",
    "    # ──────────────────────────────────────────\n",
    "    #  Sauvegarder les résultats en CSV\n",
    "    # ──────────────────────────────────────────\n",
    "    def sauvegarder(self):\n",
    "        if not self.resultats:\n",
    "            print(f\"  ⚠️  Aucune donnée à sauvegarder pour {self.nom_source}\")\n",
    "            return None\n",
    "\n",
    "        nom_fichier = self.nom_source.lower().replace(\" \", \"_\").replace(\"/\", \"_\")\n",
    "        chemin = f\"data/raw/{nom_fichier}.csv\"\n",
    "\n",
    "        df = pd.DataFrame(self.resultats)\n",
    "        df.to_csv(chemin, index=False, encoding=\"utf-8\")\n",
    "        print(f\"  💾 {len(df)} enregistrements → {chemin}\")\n",
    "        return chemin\n",
    "\n",
    "    # ──────────────────────────────────────────\n",
    "    #  Méthode abstraite : à implémenter par chaque scraper\n",
    "    # ──────────────────────────────────────────\n",
    "    @abstractmethod\n",
    "    def scrape(self) -> list:\n",
    "        \"\"\"\n",
    "        Logique de scraping spécifique au site.\n",
    "        Doit retourner une liste de dicts normalisés.\n",
    "        \"\"\"\n",
    "        pass\n",
    "\n",
    "    # ──────────────────────────────────────────\n",
    "    #  Lancer le scraper\n",
    "    # ──────────────────────────────────────────\n",
    "    def run(self):\n",
    "        print(f\"\\n{'─' * 55}\")\n",
    "        print(f\"  🌐 Scraper : {self.nom_source}\")\n",
    "        print(f\"{'─' * 55}\")\n",
    "\n",
    "        self.resultats = self.scrape()\n",
    "\n",
    "        chemin = self.sauvegarder()\n",
    "        print(f\"  ✅ {self.nom_source} terminé — {len(self.resultats)} profils\")\n",
    "        return self.resultats"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
