{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "024d219d-560f-41a1-9520-908379a7c54c",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "=======================================================\n",
    "  SCRAPER CORRIGÉ — www.influenceurs.tn\n",
    "  \n",
    "  BUGS CORRIGÉS :\n",
    "  ✅ Bug 1 : username contient l'URL complète\n",
    "             → Extraction propre depuis href uniquement\n",
    "  ✅ Bug 2 : Seulement 16 résultats\n",
    "             → Le site charge les 500 via JavaScript (scroll infini)\n",
    "             → Utilisation de Selenium pour tout charger\n",
    "  ✅ Bug 3 : stat_1 / stat_2 restent en texte \"16.7M +\"\n",
    "             → Conversion immédiate en entier\n",
    "  \n",
    "  INSTALLATION :\n",
    "    pip install selenium pandas\n",
    "    + Télécharger ChromeDriver : https://chromedriver.chromium.org/\n",
    "      (même version que ton Chrome)\n",
    "=======================================================\n",
    "\"\"\"\n",
    "\n",
    "import time\n",
    "import re\n",
    "import os\n",
    "import json\n",
    "import pandas as pd\n",
    "from datetime import datetime\n",
    "\n",
    "# ── Selenium ──\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.options import Options\n",
    "from selenium.webdriver.chrome.service import Service\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from selenium.webdriver.support import expected_conditions as EC\n",
    "from selenium.common.exceptions import TimeoutException, NoSuchElementException\n",
    "\n",
    "\n",
    "BASE_URL = \"https://www.influenceurs.tn\"\n",
    "\n",
    "\n",
    "# ──────────────────────────────────────────────────────\n",
    "#  CONVERTIR \"16.7M +\" → 16700000\n",
    "# ──────────────────────────────────────────────────────\n",
    "def convertir_stat(valeur_str):\n",
    "    \"\"\"\n",
    "    ✅ BUG 3 CORRIGÉ : conversion immédiate en entier\n",
    "    \"16.7M +\" → 16700000\n",
    "    \"819.7K +\"→ 819700\n",
    "    \"3.3K\"    → 3300\n",
    "    \"893\"     → 893\n",
    "    \"\"        → 0\n",
    "    \"\"\"\n",
    "    if not valeur_str:\n",
    "        return 0\n",
    "    s = str(valeur_str).upper().replace(\" \", \"\").replace(\"+\", \"\").strip()\n",
    "    try:\n",
    "        if \"M\" in s:\n",
    "            return int(float(s.replace(\"M\", \"\")) * 1_000_000)\n",
    "        elif \"K\" in s:\n",
    "            return int(float(s.replace(\"K\", \"\")) * 1_000)\n",
    "        else:\n",
    "            return int(float(s.replace(\",\", \".\")))\n",
    "    except (ValueError, AttributeError):\n",
    "        return 0\n",
    "\n",
    "\n",
    "# ──────────────────────────────────────────────────────\n",
    "#  INITIALISER LE NAVIGATEUR SELENIUM\n",
    "# ──────────────────────────────────────────────────────\n",
    "def init_driver(headless=True):\n",
    "    \"\"\"\n",
    "    Lance Chrome en mode silencieux (headless).\n",
    "    Si tu veux voir le navigateur : headless=False\n",
    "    \"\"\"\n",
    "    options = Options()\n",
    "    if headless:\n",
    "        options.add_argument(\"--headless=new\")\n",
    "    options.add_argument(\"--no-sandbox\")\n",
    "    options.add_argument(\"--disable-dev-shm-usage\")\n",
    "    options.add_argument(\"--disable-blink-features=AutomationControlled\")\n",
    "    options.add_argument(\"--window-size=1920,1080\")\n",
    "    options.add_argument(\n",
    "        \"user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) \"\n",
    "        \"AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36\"\n",
    "    )\n",
    "    # Masquer que c'est Selenium\n",
    "    options.add_experimental_option(\"excludeSwitches\", [\"enable-automation\"])\n",
    "    options.add_experimental_option(\"useAutomationExtension\", False)\n",
    "\n",
    "    driver = webdriver.Chrome(options=options)\n",
    "    driver.execute_script(\"Object.defineProperty(navigator, 'webdriver', {get: () => undefined})\")\n",
    "    return driver\n",
    "\n",
    "\n",
    "# ──────────────────────────────────────────────────────\n",
    "#  ✅ BUG 2 CORRIGÉ : Scroll infini pour charger les 500\n",
    "# ──────────────────────────────────────────────────────\n",
    "def charger_tous_les_influenceurs(driver):\n",
    "    \"\"\"\n",
    "    Le site charge les influenceurs par lots via scroll infini.\n",
    "    On scroll jusqu'en bas plusieurs fois jusqu'à ce que\n",
    "    le nombre de cartes ne change plus.\n",
    "    \"\"\"\n",
    "    print(\"  🔄 Chargement de la page...\")\n",
    "    driver.get(BASE_URL + \"/\")\n",
    "    time.sleep(3)\n",
    "\n",
    "    nb_precedent = 0\n",
    "    tentatives_sans_changement = 0\n",
    "    MAX_SANS_CHANGEMENT = 3   # Arrêter après 3 scrolls sans nouveaux résultats\n",
    "\n",
    "    print(\"  📜 Scroll infini pour charger tous les profils...\")\n",
    "\n",
    "    while tentatives_sans_changement < MAX_SANS_CHANGEMENT:\n",
    "        # Compter les cartes actuellement chargées\n",
    "        cartes = driver.find_elements(By.XPATH, \"//a[text()='Voir plus']\")\n",
    "        nb_actuel = len(cartes)\n",
    "\n",
    "        print(f\"     → {nb_actuel} profils chargés...\", end=\"\\r\")\n",
    "\n",
    "        if nb_actuel == nb_precedent:\n",
    "            tentatives_sans_changement += 1\n",
    "        else:\n",
    "            tentatives_sans_changement = 0\n",
    "            nb_precedent = nb_actuel\n",
    "\n",
    "        # Scroller jusqu'en bas de la page\n",
    "        driver.execute_script(\"window.scrollTo(0, document.body.scrollHeight);\")\n",
    "        time.sleep(2)\n",
    "\n",
    "        # Aussi cliquer sur \"charger plus\" si ce bouton existe\n",
    "        try:\n",
    "            btn = driver.find_element(By.XPATH, \"//button[contains(text(), 'plus') or contains(text(), 'more')]\")\n",
    "            driver.execute_script(\"arguments[0].click();\", btn)\n",
    "            time.sleep(2)\n",
    "        except NoSuchElementException:\n",
    "            pass\n",
    "\n",
    "    print(f\"\\n  ✅ {nb_actuel} profils chargés au total\")\n",
    "    return nb_actuel\n",
    "\n",
    "\n",
    "# ──────────────────────────────────────────────────────\n",
    "#  ✅ BUG 1 CORRIGÉ : Extraction propre des cartes\n",
    "# ──────────────────────────────────────────────────────\n",
    "def extraire_cartes(driver):\n",
    "    \"\"\"\n",
    "    Extrait les données de toutes les cartes visibles.\n",
    "    \n",
    "    BUG 1 CORRIGÉ : username extrait proprement depuis le href\n",
    "    Avant (buggé)  : \"fluenceurs.tndorra_zarrouk\"\n",
    "    Après (corrigé): \"dorra_zarrouk\"\n",
    "    \"\"\"\n",
    "    cartes = []\n",
    "\n",
    "    # Trouver tous les boutons \"Voir plus\"\n",
    "    liens_voir_plus = driver.find_elements(By.XPATH, \"//a[text()='Voir plus']\")\n",
    "    print(f\"\\n  🔍 Extraction de {len(liens_voir_plus)} cartes...\")\n",
    "\n",
    "    for lien in liens_voir_plus:\n",
    "        try:\n",
    "            href = lien.get_attribute(\"href\") or \"\"\n",
    "\n",
    "            # ✅ BUG 1 FIX : extraire uniquement le username depuis l'URL\n",
    "            # href = \"https://www.influenceurs.tn/influencer/show/dorra_zarrouk\"\n",
    "            # username = \"dorra_zarrouk\"\n",
    "            username = href.split(\"/influencer/show/\")[-1].strip(\"/\")\n",
    "\n",
    "            # Remonter dans le DOM pour trouver le conteneur parent\n",
    "            conteneur = lien\n",
    "            nom = \"\"\n",
    "            categorie = \"\"\n",
    "            stats = []\n",
    "\n",
    "            for _ in range(8):  # Remonter jusqu'à 8 niveaux\n",
    "                try:\n",
    "                    conteneur = conteneur.find_element(By.XPATH, \"..\")\n",
    "                    # Chercher nom (h3) et catégorie (h4)\n",
    "                    try:\n",
    "                        nom_el = conteneur.find_element(By.TAG_NAME, \"h3\")\n",
    "                        nom = nom_el.text.strip()\n",
    "                    except NoSuchElementException:\n",
    "                        pass\n",
    "                    try:\n",
    "                        cat_el = conteneur.find_element(By.TAG_NAME, \"h4\")\n",
    "                        categorie = cat_el.text.strip()\n",
    "                    except NoSuchElementException:\n",
    "                        pass\n",
    "                    # Chercher les stats (li)\n",
    "                    li_elements = conteneur.find_elements(By.TAG_NAME, \"li\")\n",
    "                    if li_elements:\n",
    "                        stats = [li.text.strip() for li in li_elements if li.text.strip()]\n",
    "                    # Arrêter si on a tout\n",
    "                    if nom and categorie and stats:\n",
    "                        break\n",
    "                except Exception:\n",
    "                    break\n",
    "\n",
    "            if not username:\n",
    "                continue\n",
    "\n",
    "            # ✅ BUG 3 FIX : convertir immédiatement les stats en entiers\n",
    "            ig_followers = convertir_stat(stats[0]) if len(stats) > 0 else 0\n",
    "            tk_followers = convertir_stat(stats[1]) if len(stats) > 1 else 0\n",
    "\n",
    "            cartes.append({\n",
    "                \"username\":            username,          # ✅ propre\n",
    "                \"nom\":                 nom,\n",
    "                \"categorie\":           categorie,\n",
    "                \"instagram_followers\": ig_followers,      # ✅ entier\n",
    "                \"tiktok_followers\":    tk_followers,      # ✅ entier\n",
    "                \"url_profil\":          href,              # ✅ URL complète\n",
    "                \"photo_url\":           f\"{BASE_URL}/uploads/{username}.jpg\",\n",
    "            })\n",
    "\n",
    "        except Exception as e:\n",
    "            continue\n",
    "\n",
    "    print(f\"  ✅ {len(cartes)} cartes extraites avec succès\")\n",
    "    return cartes\n",
    "\n",
    "\n",
    "# ──────────────────────────────────────────────────────\n",
    "#  SCRAPER LES PROFILS INDIVIDUELS\n",
    "# ──────────────────────────────────────────────────────\n",
    "def scraper_profil(driver, username):\n",
    "    \"\"\"Scrape la page détail d'un influenceur\"\"\"\n",
    "    url = f\"{BASE_URL}/influencer/show/{username}\"\n",
    "    try:\n",
    "        driver.get(url)\n",
    "        time.sleep(1.5)\n",
    "\n",
    "        # Biographie\n",
    "        bio = \"\"\n",
    "        try:\n",
    "            bio_els = driver.find_elements(By.XPATH, \"//h3[contains(text(),'Biographie')]/following-sibling::*[1]\")\n",
    "            if bio_els:\n",
    "                bio = bio_els[0].text.strip()\n",
    "        except Exception:\n",
    "            pass\n",
    "\n",
    "        # Stats détaillées : posts, ig_following, tk_following, tk_likes\n",
    "        stats_dict = {}\n",
    "        try:\n",
    "            blocs = driver.find_elements(By.XPATH, \"//h4[@class] | //h5[@class]\")\n",
    "            for bloc in blocs:\n",
    "                label = bloc.text.strip().lower()\n",
    "                try:\n",
    "                    valeur = bloc.find_element(By.XPATH, \"following-sibling::*[1]\").text.strip()\n",
    "                    stats_dict[label] = valeur\n",
    "                except Exception:\n",
    "                    pass\n",
    "        except Exception:\n",
    "            pass\n",
    "\n",
    "        # Parser dans l'ordre connu\n",
    "        labels = list(stats_dict.items())\n",
    "        result = {\n",
    "            \"biographie\":           bio,\n",
    "            \"instagram_posts\":      0,\n",
    "            \"instagram_following\":  0,\n",
    "            \"tiktok_following\":     0,\n",
    "            \"tiktok_likes\":         0,\n",
    "        }\n",
    "\n",
    "        followers_vu = 0\n",
    "        following_vu = 0\n",
    "        for label, valeur in labels:\n",
    "            if \"posts\" in label:\n",
    "                result[\"instagram_posts\"] = convertir_stat(valeur)\n",
    "            elif \"followers\" in label:\n",
    "                followers_vu += 1\n",
    "            elif \"following\" in label:\n",
    "                following_vu += 1\n",
    "                if following_vu == 1:\n",
    "                    result[\"instagram_following\"] = convertir_stat(valeur)\n",
    "                elif following_vu == 2:\n",
    "                    result[\"tiktok_following\"] = convertir_stat(valeur)\n",
    "            elif \"likes\" in label:\n",
    "                result[\"tiktok_likes\"] = convertir_stat(valeur)\n",
    "\n",
    "        return result\n",
    "\n",
    "    except Exception as e:\n",
    "        return {}\n",
    "\n",
    "\n",
    "# ──────────────────────────────────────────────────────\n",
    "#  SCORE D'INFLUENCE\n",
    "# ──────────────────────────────────────────────────────\n",
    "def calculer_score(ig_f, tk_f, ig_posts, tk_likes):\n",
    "    score = 0\n",
    "    total = ig_f + tk_f\n",
    "\n",
    "    if total > 10_000_000:  score += 40\n",
    "    elif total > 5_000_000: score += 35\n",
    "    elif total > 1_000_000: score += 28\n",
    "    elif total > 500_000:   score += 22\n",
    "    elif total > 100_000:   score += 15\n",
    "    elif total > 10_000:    score += 8\n",
    "\n",
    "    if ig_f > 0 and tk_f > 0:  score += 20\n",
    "    elif ig_f > 0 or tk_f > 0: score += 10\n",
    "\n",
    "    if tk_f > 0 and tk_likes > 0:\n",
    "        ratio = tk_likes / tk_f\n",
    "        if ratio > 20:   score += 25\n",
    "        elif ratio > 10: score += 20\n",
    "        elif ratio > 5:  score += 14\n",
    "        elif ratio > 0:  score += 8\n",
    "\n",
    "    if ig_posts > 500:    score += 15\n",
    "    elif ig_posts > 200:  score += 12\n",
    "    elif ig_posts > 50:   score += 8\n",
    "    elif ig_posts > 0:    score += 4\n",
    "\n",
    "    return min(score, 100)\n",
    "\n",
    "\n",
    "# ──────────────────────────────────────────────────────\n",
    "#  PROGRAMME PRINCIPAL\n",
    "# ──────────────────────────────────────────────────────\n",
    "def main():\n",
    "    print(\"\\n\" + \"=\" * 60)\n",
    "    print(\"  🚀 SCRAPER CORRIGÉ — influenceurs.tn\")\n",
    "    print(\"=\" * 60)\n",
    "    print(\"  Bugs corrigés :\")\n",
    "    print(\"  ✅ Username propre (plus d'URL dans le nom)\")\n",
    "    print(\"  ✅ Scroll infini → tous les 500 profils\")\n",
    "    print(\"  ✅ Stats converties en entiers\")\n",
    "    print(\"=\" * 60)\n",
    "\n",
    "    os.makedirs(\"data\", exist_ok=True)\n",
    "\n",
    "    # Initialiser Selenium\n",
    "    print(\"\\n  🌐 Lancement du navigateur Chrome...\")\n",
    "    driver = init_driver(headless=True)   # headless=False pour voir le navigateur\n",
    "\n",
    "    try:\n",
    "        # ── PHASE 1 : Charger tous les influenceurs ──\n",
    "        charger_tous_les_influenceurs(driver)\n",
    "\n",
    "        # ── PHASE 2 : Extraire toutes les cartes ──\n",
    "        cartes = extraire_cartes(driver)\n",
    "\n",
    "        if not cartes:\n",
    "            print(\"❌ Aucune carte trouvée. Vérifier le site.\")\n",
    "            return\n",
    "\n",
    "        # ── PHASE 3 : Scraper chaque profil détaillé ──\n",
    "        print(f\"\\n{'=' * 60}\")\n",
    "        print(f\"  📄 Scraping des {len(cartes)} profils individuels...\")\n",
    "        print(f\"{'=' * 60}\")\n",
    "\n",
    "        resultats = []\n",
    "        for i, carte in enumerate(cartes, 1):\n",
    "            username = carte[\"username\"]\n",
    "            print(f\"  [{i:>3}/{len(cartes)}] @{username:<30}\", end=\" \")\n",
    "\n",
    "            details = scraper_profil(driver, username)\n",
    "\n",
    "            ig_f  = carte[\"instagram_followers\"]\n",
    "            tk_f  = carte[\"tiktok_followers\"]\n",
    "            ig_p  = details.get(\"instagram_posts\", 0)\n",
    "            tk_l  = details.get(\"tiktok_likes\", 0)\n",
    "            score = calculer_score(ig_f, tk_f, ig_p, tk_l)\n",
    "\n",
    "            record = {\n",
    "                \"username\":            username,\n",
    "                \"nom\":                 carte[\"nom\"],\n",
    "                \"categorie\":           carte[\"categorie\"],\n",
    "                \"biographie\":          details.get(\"biographie\", \"\"),\n",
    "                \"instagram_followers\": ig_f,\n",
    "                \"instagram_following\": details.get(\"instagram_following\", 0),\n",
    "                \"instagram_posts\":     ig_p,\n",
    "                \"tiktok_followers\":    tk_f,\n",
    "                \"tiktok_following\":    details.get(\"tiktok_following\", 0),\n",
    "                \"tiktok_likes\":        tk_l,\n",
    "                \"score_influence\":     score,\n",
    "                \"url_profil\":          carte[\"url_profil\"],\n",
    "                \"photo_url\":           carte[\"photo_url\"],\n",
    "                \"source\":              \"influenceurs.tn\",\n",
    "                \"date_collecte\":       datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\"),\n",
    "            }\n",
    "            resultats.append(record)\n",
    "\n",
    "            print(f\"IG:{ig_f:>10,} | TK:{tk_f:>10,} | Score:{score:>3}/100\")\n",
    "\n",
    "            # Sauvegarde progressive toutes les 50 lignes\n",
    "            if i % 50 == 0:\n",
    "                df_temp = pd.DataFrame(resultats)\n",
    "                df_temp.to_csv(\"data/influenceurs_tn_progress.csv\", index=False, encoding=\"utf-8\")\n",
    "                print(f\"  💾 Sauvegarde intermédiaire : {i} profils\")\n",
    "\n",
    "    finally:\n",
    "        driver.quit()\n",
    "        print(\"\\n  🔒 Navigateur fermé\")\n",
    "\n",
    "    # ── PHASE 4 : Sauvegarder le dataset final ──\n",
    "    print(f\"\\n{'=' * 60}\")\n",
    "    print(\"  💾 Sauvegarde finale...\")\n",
    "    print(f\"{'=' * 60}\")\n",
    "\n",
    "    df = pd.DataFrame(resultats)\n",
    "    df = df.sort_values(\"score_influence\", ascending=False).reset_index(drop=True)\n",
    "\n",
    "    df.to_csv(\"data/influenceurs_tn.csv\", index=False, encoding=\"utf-8\")\n",
    "    with open(\"data/influenceurs_tn.json\", \"w\", encoding=\"utf-8\") as f:\n",
    "        json.dump(resultats, f, ensure_ascii=False, indent=2)\n",
    "\n",
    "    # ── Résumé ──\n",
    "    print(f\"\\n  ✅ {len(df)} influenceurs collectés\")\n",
    "    print(f\"  📊 Colonnes : {list(df.columns)}\")\n",
    "    print(f\"\\n  🏆 TOP 10 :\")\n",
    "    cols = [\"username\", \"nom\", \"categorie\", \"instagram_followers\", \"tiktok_followers\", \"score_influence\"]\n",
    "    print(df[cols].head(10).to_string(index=False))\n",
    "\n",
    "    print(f\"\\n  📂 Par catégorie :\")\n",
    "    print(df.groupby(\"categorie\")[\"username\"].count().sort_values(ascending=False).to_string())\n",
    "\n",
    "    print(f\"\\n  ✅ Fichier sauvegardé : data/influenceurs_tn.csv\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
