{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b4de7c4f-37f8-4826-a364-247d513bcbd7",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "=======================================================\n",
    "  SCRAPER — Sites de presse tunisiens\n",
    "  mosaiquefm.net | businessnews.com.tn | leaders.com.tn\n",
    "  Hérite de BaseScraper\n",
    "  Données : articles mentionnant des influenceurs / digital\n",
    "=======================================================\n",
    "\"\"\"\n",
    "\n",
    "import re\n",
    "import sys\n",
    "import os\n",
    "sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))\n",
    "\n",
    "from scrapers.base_scraper import BaseScraper\n",
    "\n",
    "\n",
    "class PresseTunisienneScraper(BaseScraper):\n",
    "\n",
    "    SITES = [\n",
    "        {\n",
    "            \"nom\":  \"mosaiquefm\",\n",
    "            \"url\":  \"https://www.mosaiquefm.net/fr/actualite/societe\",\n",
    "            \"base\": \"https://www.mosaiquefm.net\",\n",
    "        },\n",
    "        {\n",
    "            \"nom\":  \"businessnews\",\n",
    "            \"url\":  \"https://www.businessnews.com.tn/cat/digital-economie-numerique\",\n",
    "            \"base\": \"https://www.businessnews.com.tn\",\n",
    "        },\n",
    "        {\n",
    "            \"nom\":  \"leaders\",\n",
    "            \"url\":  \"https://www.leaders.com.tn/rubrique/23-digital\",\n",
    "            \"base\": \"https://www.leaders.com.tn\",\n",
    "        },\n",
    "    ]\n",
    "\n",
    "    # Mots-clés qui signalent qu'un article parle d'influenceurs\n",
    "    MOTS_CLES = [\n",
    "        \"influenceur\", \"influencer\", \"instagram\", \"tiktok\",\n",
    "        \"youtuber\", \"réseaux sociaux\", \"créateur\", \"digital\",\n",
    "        \"marketing\", \"blogger\", \"vlogger\"\n",
    "    ]\n",
    "\n",
    "    def __init__(self):\n",
    "        # Les articles de presse ne suivent PAS le schéma influenceurs\n",
    "        # On les stocke dans un fichier séparé\n",
    "        super().__init__(nom_source=\"presse_tunisienne\", pause=3)\n",
    "\n",
    "    def scrape(self):\n",
    "        \"\"\"\n",
    "        Pour la presse, on retourne des articles (pas des profils).\n",
    "        Le schéma est différent — on surcharge sauvegarder() pour ça.\n",
    "        \"\"\"\n",
    "        tous_articles = []\n",
    "\n",
    "        for site in self.SITES:\n",
    "            print(f\"  📰 Scraping {site['nom']}...\")\n",
    "            articles = self._scraper_site(site)\n",
    "            tous_articles.extend(articles)\n",
    "            print(f\"     → {len(articles)} articles trouvés\")\n",
    "\n",
    "        # Sauvegarder les articles séparément (pas dans data/raw/ influenceurs)\n",
    "        import pandas as pd\n",
    "        os.makedirs(\"data/raw\", exist_ok=True)\n",
    "        df = pd.DataFrame(tous_articles)\n",
    "        df.to_csv(\"data/raw/articles_presse.csv\", index=False, encoding=\"utf-8\")\n",
    "        print(f\"  💾 {len(df)} articles → data/raw/articles_presse.csv\")\n",
    "\n",
    "        # Retourner liste vide pour le pipeline (articles ≠ influenceurs)\n",
    "        return []\n",
    "\n",
    "    def _scraper_site(self, site):\n",
    "        response = self.get(site[\"url\"])\n",
    "        if not response:\n",
    "            return []\n",
    "\n",
    "        soup = self.parse(response)\n",
    "        articles = []\n",
    "\n",
    "        blocs = soup.find_all([\"article\", \"div\"], class_=re.compile(r\"article|item|post|news\", re.I))\n",
    "        if not blocs:\n",
    "            blocs = soup.find_all(\"article\")\n",
    "\n",
    "        for bloc in blocs[:30]:\n",
    "            titre_tag = bloc.find([\"h2\", \"h3\", \"h4\"])\n",
    "            lien_tag  = bloc.find(\"a\", href=True)\n",
    "            if not titre_tag:\n",
    "                continue\n",
    "\n",
    "            titre = titre_tag.get_text(strip=True)\n",
    "            lien  = lien_tag[\"href\"] if lien_tag else \"\"\n",
    "            if lien and not lien.startswith(\"http\"):\n",
    "                lien = site[\"base\"] + lien\n",
    "\n",
    "            # Garder uniquement les articles pertinents\n",
    "            if self._est_pertinent(titre):\n",
    "                articles.append({\n",
    "                    \"source\":        site[\"nom\"],\n",
    "                    \"titre\":         titre,\n",
    "                    \"lien\":          lien,\n",
    "                    \"date_collecte\": self._now(),\n",
    "                })\n",
    "\n",
    "        return articles\n",
    "\n",
    "    def _est_pertinent(self, titre):\n",
    "        titre_lower = titre.lower()\n",
    "        return any(mot in titre_lower for mot in self.MOTS_CLES)\n",
    "\n",
    "    def _now(self):\n",
    "        from datetime import datetime\n",
    "        return datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
