{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ea8c2e2f-3086-4904-9d8f-a2f73d603d64",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "=======================================================\n",
    "  SCRAPER — socialblade.com  (Top Tunisie)\n",
    "  Hérite de BaseScraper\n",
    "  Données : classements Instagram + YouTube + Twitter TN\n",
    "=======================================================\n",
    "\"\"\"\n",
    "\n",
    "import re\n",
    "import sys\n",
    "import os\n",
    "sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))\n",
    "\n",
    "from scrapers.base_scraper import BaseScraper\n",
    "\n",
    "\n",
    "class SocialBladeScraper(BaseScraper):\n",
    "\n",
    "    URLS = {\n",
    "        \"instagram\": \"https://socialblade.com/instagram/top/100/country/TN\",\n",
    "        \"youtube\":   \"https://socialblade.com/youtube/top/100/country/TN\",\n",
    "        \"twitter\":   \"https://socialblade.com/twitter/top/100/country/TN\",\n",
    "    }\n",
    "\n",
    "    def __init__(self):\n",
    "        super().__init__(nom_source=\"socialblade.com\", pause=3)\n",
    "\n",
    "    def scrape(self):\n",
    "        resultats = []\n",
    "        for plateforme, url in self.URLS.items():\n",
    "            print(f\"  📡 Scraping {plateforme}...\")\n",
    "            data = self._scraper_classement(url, plateforme)\n",
    "            resultats.extend(data)\n",
    "            print(f\"     → {len(data)} comptes trouvés\")\n",
    "\n",
    "        return resultats\n",
    "\n",
    "    def _scraper_classement(self, url, plateforme):\n",
    "        response = self.get(url)\n",
    "        if not response:\n",
    "            return []\n",
    "\n",
    "        soup = self.parse(response)\n",
    "        resultats = []\n",
    "\n",
    "        # SocialBlade : chaque ligne de classement a un id \"socialblade-user-XXXX\"\n",
    "        rows = soup.find_all(\"div\", id=re.compile(r\"socialblade-user-\"))\n",
    "\n",
    "        for row in rows:\n",
    "            # Username\n",
    "            username_tag = row.find(\"a\", href=re.compile(rf\"/{plateforme}/user/\"))\n",
    "            if not username_tag:\n",
    "                continue\n",
    "            username = username_tag.get_text(strip=True).strip(\"@\")\n",
    "\n",
    "            # Followers\n",
    "            spans = row.find_all(\"span\")\n",
    "            followers = 0\n",
    "            for span in spans:\n",
    "                txt = span.get_text(strip=True)\n",
    "                if re.match(r\"[\\d,.]+[KMB]?\", txt):\n",
    "                    followers = self.convertir_stat(txt)\n",
    "                    break\n",
    "\n",
    "            # Construire le record selon la plateforme\n",
    "            data = {\"username\": username, \"url_profil\": f\"https://socialblade.com/{plateforme}/user/{username}\"}\n",
    "            if plateforme == \"instagram\":\n",
    "                data[\"instagram_followers\"] = followers\n",
    "            elif plateforme == \"youtube\":\n",
    "                data[\"youtube_subscribers\"] = followers\n",
    "            elif plateforme == \"twitter\":\n",
    "                data[\"twitter_followers\"] = followers\n",
    "\n",
    "            resultats.append(self.normaliser(data))\n",
    "\n",
    "        return resultats"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
